services:
  - type: web
    name: stdata
    env: python
    pythonVersion: 3.11.7
    buildCommand: |
      python -m pip install --upgrade pip && \
      python -m pip install -r requirements.txt
    startCommand: gunicorn app:app
    autoDeploy: true
    plan: free
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        value: your-secret-key-here
